apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: peertask
resources:
  - namespace.yaml
  - configmap.yaml
  - postgres.yaml
  - api.yaml
  - ingress.yaml
images:
  - name: ghcr.io/minhduy6868/peer_task_server
    newTag: latest
